/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as TecidoRouteImport } from './routes/tecido'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const TecidoRoute = TecidoRouteImport.update({
  id: '/tecido',
  path: '/tecido',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/loja': typeof LojaRoute
  '/tecido': typeof TecidoRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/loja': typeof LojaRoute
  '/tecido': typeof TecidoRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/loja': typeof LojaRoute
  '/tecido': typeof TecidoRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/loja' | '/tecido' | '/api/public/asaas-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/loja' | '/tecido' | '/api/public/asaas-webhook'
  id: '__root__' | '/' | '/loja' | '/tecido' | '/api/public/asaas-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LojaRoute: typeof LojaRoute
  TecidoRoute: typeof TecidoRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecido': {
      id: '/tecido'
      path: '/tecido'
      fullPath: '/tecido'
      preLoaderRoute: typeof TecidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LojaRoute: LojaRoute,
  TecidoRoute: TecidoRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
